[tool.poetry]
name = "github_bwf"
version = "0.1.0"
description = ""
authors = ["Daniel Haeupl <daniel.haeupl@mpl.mpg.de>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
numpy = "^1.24.1"
scipy = "^1.10.0"
sympy = "^1.11.1"
ARC-Alkali-Rydberg-Calculator = "^3.2.6"
wxPython = "^4.2.0"
symengine = "^0.11.0"
psutil = "^6.0.0"
notebook = "^7.2.2"
jupyterlab = "^4.2.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
